name: Deploy front

on:
    push:
        branches:
            - main
    
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            if: github.ref == 'refs/head/main'
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./Cinema-Front-SemFramework
